CREATE TABLE IF NOT EXISTS game (
  id BOOLEAN PRIMARY KEY DEFAULT TRUE,
  func TEXT NOT NULL,
  description TEXT NOT NULL,
  args INTEGER NOT NULL,
  input TEXT NOT NULL,
  output TEXT NOT NULL,
  nix_commit TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
