CREATE TABLE IF NOT EXISTS game (
  id INTEGER PRIMARY KEY CHECK (id IN (0,1)) DEFAULT 1,
  func TEXT NOT NULL,
  description TEXT NOT NULL,
  args INTEGER NOT NULL,
  input TEXT NOT NULL,
  output TEXT NOT NULL,
  nix_commit TEXT NOT NULL,
  created_at DATETIME DEFAULT (CURRENT_TIMESTAMP)
);
